
package ui;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.BorderFactory;
import javax.swing.JPanel;
import javax.swing.JFrame;
import utils.UserSession;


public class FenAppUI extends javax.swing.JFrame {

    /**
     * Creates new form FinanceAppUI
     */
    public FenAppUI() {
        initComponents();
        setClientNameLabel();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        background = background =  new JPanel() {
            public void paintComponent(Graphics g) {
                Image img = Toolkit.getDefaultToolkit().getImage(
                    FenConnection.class.getResource("/img/background.png"));
                g.drawImage(img, 0, 0, this.getWidth(), this.getHeight(), this);
            }
        };
        lblTitle = new javax.swing.JLabel();
        lblClientName = new javax.swing.JLabel();
        btnSeeExpenses = new javax.swing.JButton();
        btnAddExpenses = new javax.swing.JButton();
        btnAddViewBills = new javax.swing.JButton();
        btnYouOwe = new javax.swing.JButton();
        btnDisconnect = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Page d'acceuil");
        setResizable(false);

        lblTitle.setFont(new java.awt.Font("Dialog", 1, 80)); // NOI18N
        lblTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/welcomeBanner.png"))); // NOI18N

        lblClientName.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        lblClientName.setForeground(new java.awt.Color(255, 255, 255));
        lblClientName.setText("x");

        btnSeeExpenses.setBackground(new java.awt.Color(25, 23, 36));
        btnSeeExpenses.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnSeeExpenses.setForeground(new java.awt.Color(255, 255, 255));
        btnSeeExpenses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnSeeExpenses.png"))); // NOI18N
        btnSeeExpenses.setBorder(BorderFactory.createBevelBorder(0));
        btnSeeExpenses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeeExpensesActionPerformed(evt);
            }
        });

        btnAddExpenses.setBackground(new java.awt.Color(25, 23, 36));
        btnAddExpenses.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnAddExpenses.setForeground(new java.awt.Color(255, 255, 255));
        btnAddExpenses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnAddExpenses.png"))); // NOI18N
        btnAddExpenses.setBorder(BorderFactory.createBevelBorder(0));
        btnAddExpenses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddExpensesActionPerformed(evt);
            }
        });

        btnAddViewBills.setBackground(new java.awt.Color(25, 23, 36));
        btnAddViewBills.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnAddViewBills.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnAddViewBillsTransparent.png"))); // NOI18N
        btnAddViewBills.setBorder(BorderFactory.createBevelBorder(0));
        btnAddViewBills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddViewBillsActionPerformed(evt);
            }
        });

        btnYouOwe.setBackground(new java.awt.Color(25, 23, 36));
        btnYouOwe.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnYouOwe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnWhoOwesWho.png"))); // NOI18N
        btnYouOwe.setBorder(BorderFactory.createBevelBorder(0));
        btnYouOwe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYouOweActionPerformed(evt);
            }
        });

        btnDisconnect.setBackground(new java.awt.Color(255, 102, 196));
        btnDisconnect.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnDisconnect.setForeground(new java.awt.Color(0, 0, 0));
        btnDisconnect.setText("Disconnect");
        btnDisconnect.setBorder(BorderFactory.createBevelBorder(0));
        btnDisconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisconnectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddViewBills, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddExpenses, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnYouOwe)
                            .addComponent(btnSeeExpenses)))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                        .addComponent(lblClientName)
                        .addGap(129, 129, 129))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                        .addComponent(btnDisconnect)
                        .addContainerGap())))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblClientName, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAddExpenses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSeeExpenses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAddViewBills, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnYouOwe, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(btnDisconnect)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddExpensesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddExpensesActionPerformed
        FenAddExpense fenAddExpense = new FenAddExpense();
        fenAddExpense.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAddExpensesActionPerformed

    private void btnAddViewBillsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddViewBillsActionPerformed
        FenBills fenBills = new FenBills();
        fenBills.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAddViewBillsActionPerformed

    private void btnYouOweActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYouOweActionPerformed
        FenOwing fenOwing = new FenOwing();
        fenOwing.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnYouOweActionPerformed

    private void btnDisconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisconnectActionPerformed
        FenConnection fenConnection = new FenConnection();
        fenConnection.setVisible(true);
        fenConnection.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnDisconnectActionPerformed

    private void btnSeeExpensesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeeExpensesActionPerformed
        FenExpenses fenExpenses = new FenExpenses();
        fenExpenses.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSeeExpensesActionPerformed
    
    /* 
        Change le nom au dessous du message de bienvenue, 
        selon le nom du client connecté
    */
    private void setClientNameLabel(){
        UserSession.client.getName();
        lblClientName.setText(UserSession.client.getName());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnAddExpenses;
    private javax.swing.JButton btnAddViewBills;
    private javax.swing.JButton btnDisconnect;
    private javax.swing.JButton btnSeeExpenses;
    private javax.swing.JButton btnYouOwe;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblClientName;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables

}
