/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JFrame;
import utils.UserSession;

/**
 *
 * @author Jones
 */
public class FenAppUI extends javax.swing.JFrame {

    /**
     * Creates new form FinanceAppUI
     */
    public FenAppUI() {
        initComponents();
        setClientNameLabel();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblClientName = new javax.swing.JLabel();
        btnSeeExpenses = new javax.swing.JButton();
        btnAddExpenses = new javax.swing.JButton();
        btnAddViewBills = new javax.swing.JButton();
        btnYouOwe = new javax.swing.JButton();
        btnDisconnect = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Page d'acceuil");

        lblTitle.setFont(new java.awt.Font("Dialog", 1, 80)); // NOI18N
        lblTitle.setText("Bienvenue");

        lblClientName.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        lblClientName.setText("\"client's name\"");

        btnSeeExpenses.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnSeeExpenses.setText("See expenses");

        btnAddExpenses.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnAddExpenses.setText("Add expense");
        btnAddExpenses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddExpensesActionPerformed(evt);
            }
        });

        btnAddViewBills.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnAddViewBills.setText("Add / View bills");
        btnAddViewBills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddViewBillsActionPerformed(evt);
            }
        });

        btnYouOwe.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnYouOwe.setText("You owe...");
        btnYouOwe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYouOweActionPerformed(evt);
            }
        });

        btnDisconnect.setText("Disconnect");
        btnDisconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisconnectActionPerformed(evt);
            }
        });

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentsMenuItem.setMnemonic('c');
        contentsMenuItem.setText("Contents");
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddViewBills, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddExpenses, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblClientName)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnYouOwe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSeeExpenses, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDisconnect))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblClientName, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSeeExpenses, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddExpenses, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnYouOwe, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddViewBills, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnDisconnect)
                .addGap(15, 15, 15))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddExpensesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddExpensesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddExpensesActionPerformed

    private void btnAddViewBillsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddViewBillsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddViewBillsActionPerformed

    private void btnYouOweActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYouOweActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnYouOweActionPerformed

    private void btnDisconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisconnectActionPerformed
        FenConnection fenConnection = new FenConnection();
        fenConnection.setVisible(true);
        fenConnection.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnDisconnectActionPerformed
    
    private void setClientNameLabel(){
        UserSession.client.getName();
        lblClientName.setText(UserSession.client.getName());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JButton btnAddExpenses;
    private javax.swing.JButton btnAddViewBills;
    private javax.swing.JButton btnDisconnect;
    private javax.swing.JButton btnSeeExpenses;
    private javax.swing.JButton btnYouOwe;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblClientName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
