/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import modele.ExpenseTableModel;
import modele.FactureTableModel;
import modele.ListeFacture;
import modele.ListeTransaction;
import utils.FileManip;
import utils.UserSession;

/**
 *
 * @author Jones
 */
public class FenExpenses extends javax.swing.JFrame {
    public  ListeTransaction onLoadListeTransaction = FileManip.lireFichierTransaction(UserSession.client);

    

    /**
     * Creates new form FenTable
     */
    public FenExpenses() {
        initComponents();
        UserSession.transactionsCount = expensesTable.getRowCount();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        expensesTable = new javax.swing.JTable();
        btnMenuPrincipal = new javax.swing.JButton();
        lblTitre = new javax.swing.JLabel();
        btnAddExpense = new javax.swing.JButton();
        btnDeleteRow = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("See expenses");

        onLoadListeTransaction = FileManip.lireFichierTransaction(UserSession.client);
        ExpenseTableModel model = new ExpenseTableModel(onLoadListeTransaction.getListeTransaction());
        expensesTable.setModel(model);
        jScrollPane1.setViewportView(expensesTable);

        btnMenuPrincipal.setText("Menu principal");
        btnMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuPrincipalActionPerformed(evt);
            }
        });

        lblTitre.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        lblTitre.setText("My expenses");

        btnAddExpense.setText("Add an expanse");
        btnAddExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddExpenseActionPerformed(evt);
            }
        });

        btnDeleteRow.setText("Delete");
        btnDeleteRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteRowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTitre)
                        .addGap(265, 265, 265))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAddExpense)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnMenuPrincipal))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(btnDeleteRow)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblTitre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDeleteRow)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMenuPrincipal)
                    .addComponent(btnAddExpense))
                .addGap(11, 11, 11))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuPrincipalActionPerformed
        FenAppUI fenAppUi = new FenAppUI();
        fenAppUi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMenuPrincipalActionPerformed

    private void btnAddExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddExpenseActionPerformed
        FenAddExpense fenAddExpense = new FenAddExpense();
        fenAddExpense.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAddExpenseActionPerformed

    private void btnDeleteRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteRowActionPerformed
        ExpenseTableModel model = new ExpenseTableModel(FileManip.lireFichierTransaction(UserSession.client).getListeTransaction());
        int rowIndexSelected = expensesTable.getSelectedRow();
        ListeTransaction lt = FileManip.getNewListeTransactionAfterDeletion(UserSession.client, model.getRow(rowIndexSelected));
        FileManip.ecrireListeTransactionFichier(UserSession.client, lt);
        ExpenseTableModel newModel = new ExpenseTableModel(lt.getListeTransaction());
        //newModel.fireTableRowsDeleted(rowIndexSelected, rowIndexSelected);
        expensesTable.setModel(newModel);
    }//GEN-LAST:event_btnDeleteRowActionPerformed
    
    public void refreshExpenseTable(){
        onLoadListeTransaction = FileManip.lireFichierTransaction(UserSession.client);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddExpense;
    private javax.swing.JButton btnDeleteRow;
    private javax.swing.JButton btnMenuPrincipal;
    private javax.swing.JTable expensesTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitre;
    // End of variables declaration//GEN-END:variables
}
